# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy package files and lockfile
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running lifecycle scripts
RUN pnpm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN pnpm build

# Expose port if applicable (not specified, but leaving it commented out)
# EXPOSE 3000

# Start the MCP server
CMD [ "pnpm", "start" ]
